import * as THREE from "three";
import React, { Suspense, useEffect, useRef, useState } from "react";
import { Canvas, useFrame, useLoader } from "@react-three/fiber";
import { Environment, useGLTF, ContactShadows } from "@react-three/drei";
import { useSpring } from "@react-spring/core";
import { a as three } from "@react-spring/three";
import { animated, a as web } from "@react-spring/web";
import { TextureLoader } from "three";
import { skills } from "@/data";
import CanvasLoader from "./Loader";
import { motion } from "framer-motion";
import { BackgroundGradientAnimation } from "@/components/ui/GradientBg";

function Model({ open, hinge, logoUrl, ...props }) {
	const group = useRef();
	// Load model
	const { nodes, materials } = useGLTF("/mac-draco.glb");

	const logoTexture = useLoader(TextureLoader, logoUrl);

	// Fix texture flipping issue
	logoTexture.flipY = false;

	// Take care of cursor state on hover
	const [hovered, setHovered] = useState(false);
	useEffect(() => void (document.body.style.cursor = hovered ? "pointer" : "auto"), [hovered]);

	// Make it float in the air when it's opened
	useFrame((state) => {
		const t = state.clock.getElapsedTime();
		// Apply floating effect based on whether it's open or closed
		group.current.rotation.x = THREE.MathUtils.lerp(
			group.current.rotation.x,
			Math.cos(t / 10) / 10 + (open ? 0.25 : 0), // Add a small floating effect when closed
			0.1,
		);
		group.current.rotation.y = THREE.MathUtils.lerp(
			group.current.rotation.y,
			Math.sin(t / 10) / 4 + (open ? 0.0 : 0), // Less effect when closed
			0.1,
		);
		group.current.rotation.z = THREE.MathUtils.lerp(
			group.current.rotation.z,
			Math.sin(t / 10) / 10 + (open ? 0.0 : 0), // Less effect when closed
			0.1,
		);
		group.current.position.y = THREE.MathUtils.lerp(
			group.current.position.y,
			open ? (-2 + Math.sin(t)) / 3 : -4.3 + Math.sin(t) / 3, // Add slight vertical movement when closed
			0.1,
		);
	});

	// The view was auto-generated by: https://github.com/pmndrs/gltfjsx
	// Events and spring animations were added afterwards

	return (
		<group
			ref={group}
			{...props}
			onPointerOver={(e) => (e.stopPropagation(), setHovered(true))}
			onPointerOut={(e) => setHovered(false)}
			dispose={null}
		>
			<three.group
				rotation-x={hinge}
				position={[0, -0.04, 0.41]}
			>
				<group
					position={[0, 2.96, -0.13]}
					rotation={[Math.PI / 2, 0, 0]}
				>
					<mesh
						material={materials.aluminium}
						geometry={nodes["Cube008"].geometry}
					/>
					<mesh
						material={materials["matte.001"]}
						geometry={nodes["Cube008_1"].geometry}
					/>
					<mesh geometry={nodes["Cube008_2"].geometry}>
						<meshBasicMaterial map={logoTexture} />
					</mesh>
				</group>
			</three.group>
			<mesh
				material={materials.keys}
				geometry={nodes.keyboard.geometry}
				position={[1.79, 0, 3.45]}
			/>
			<group position={[0, -0.1, 3.39]}>
				<mesh
					material={materials.aluminium}
					geometry={nodes["Cube002"].geometry}
				/>
				<mesh
					material={materials.trackpad}
					geometry={nodes["Cube002_1"].geometry}
				/>
			</group>
			<mesh
				material={materials.touchbar}
				geometry={nodes.touchbar.geometry}
				position={[0, -0.03, 1.2]}
			/>
		</group>
	);
}

const MouseClickIndicator = () => {
	return (
		<div className="relative flex flex-col items-center justify-center">
			{/* 1. The Animated Cursor */}
			<motion.div
				animate={{
					y: [0, 5, 0], // Subtle hovering
					scale: [1, 0.8, 1], // The "Click" squeeze
				}}
				transition={{
					duration: 2,
					repeat: Infinity,
					ease: "easeInOut",
				}}
				className="z-10"
			>
				<svg
					width="24"
					height="24"
					viewBox="0 0 24 24"
					fill="none"
					className="text-white drop-shadow-lg"
				>
					<path
						d="M3 3L10.07 19.97L12.58 12.58L19.97 10.07L3 3Z"
						fill="currentColor"
						stroke="black"
						strokeWidth="2"
					/>
				</svg>
			</motion.div>

			{/* 2. The "Click" Ripple/Shockwave */}
			<motion.div
				initial={{ scale: 0, opacity: 0.8 }}
				animate={{ scale: 2.5, opacity: 0 }}
				transition={{
					duration: 2,
					repeat: Infinity,
					ease: "easeOut",
					delay: 0.2, // Sync with the cursor "squeeze"
				}}
				className="absolute w-6 h-6 border-2 border-white rounded-full"
			/>
		</div>
	);
};

export default function Laptop() {
	// This flag controls open state, alternates between true & false
	const [open, setOpen] = useState(false);
	const [currentIndex, setCurrentIndex] = useState(0);

	// const handleClick = () => {
	// 	const newOpen = open.map((state, i) => (i === index ? !state : state)); // Toggle the clicked model, keep others unchanged
	// 	setOpen(newOpen);
	// };
	// We turn this into a spring animation that interpolates between 0 and 1
	const props = useSpring({ open: Number(open) });

	useEffect(() => {
		const interval = setInterval(() => {
			setCurrentIndex((prevIndex) => (prevIndex + 1) % skills.length); // Loop through the list
		}, 3000); // 3 seconds

		return () => clearInterval(interval); // Cleanup the interval on component unmount
	}, []);

	return (
		<div className="w-full h-full justify-center z-100 rounded-full">
			{!open && (
				<div className="absolute inset-0 z-[110] flex flex-col items-center pointer-events-none">
					<div className="flex-1 flex items-center justify-center">
						<motion.div
							animate={{ y: [0, -8, 0] }}
							transition={{
								duration: 1.5,
								repeat: Infinity,
								ease: "easeInOut",
							}}
							className="text-xl font-bold text-white cursor-pointer pointer-events-auto"
						>
							Click Me! ↓
						</motion.div>
					</div>

					<div
						className="absolute left-1/2 -translate-x-1/2"
						style={{ top: "78%" }}
					>
						<MouseClickIndicator />
					</div>
				</div>
			)}
			<animated.section
				style={{
					// Preserves the transition from dark blue to deep purple
					background: props.open.to([0, 1], ["#000319", "#38017d"]),
				}}
				className="h-full relative overflow-hidden"
			>
				{/* The Gradient Animation Layer */}
				<animated.div
					style={{
						opacity: props.open, // Fades from 0 to 1
						position: "absolute",
						inset: 0,
						zIndex: 0,
					}}
				>
					<BackgroundGradientAnimation>
						<div className="absolute z-50 inset-0 flex items-center justify-center text-white font-bold px-4 pointer-events-none text-3xl text-center md:text-4xl lg:text-7xl">
							{/* Your content here */}
						</div>
					</BackgroundGradientAnimation>
				</animated.div>
				<Canvas
					className="w-full h-full z-100"
					dpr={[1, 2]}
					camera={{ position: [0, 10, -100], fov: 100 }}
				>
					<three.pointLight
						position={[10, 10, 10]}
						intensity={1.5}
						color={props.open.to([0, 1], ["#000", "#d25578"])}
					/>
					<Suspense fallback={<CanvasLoader />}>
						<group
							scale={[15, 15, 5]}
							position={[0, 0, 0]}
							rotation={[0, Math.PI, 0]}
							onClick={(e) => (e.stopPropagation(), setOpen(!open))} // Handle click for the individual model
						>
							<Model
								open={open} // Pass the individual open state
								hinge={props.open.to([0, 1], [1.575, -0.425])}
								logoUrl={skills[currentIndex].logoUrl}
							/>
						</group>
						<Environment preset="city" />
					</Suspense>
					<ContactShadows
						position={[0, -4.5, 0]}
						opacity={0.4}
						scale={20}
						blur={1.75}
						far={4.5}
					/>
				</Canvas>
			</animated.section>
			{/* );
			})} */}
		</div>
	);
}
